Geddy Lucier
3/18/19
Cleaning and Incorporation of Zebra Muscle Data 

Preamble
```{r}
library(tidyverse)
library(sf)
library(terra)
library(readxl)
library(ggplot2)
library(ggforce)
library(stringr)
library(cowplot)
library(dplyr)
library(gbm)

zebra <- st_read("https://raw.githubusercontent.com/ScubaDotTech/OpenAIS/refs/heads/main/Candlewood_Lake2025/SdT-CT_AIS-Geddy-Winter-2024/zeb_msc.kml")

zebra_base <- data.frame(zebra)

```
Cleaning Initial Dataset
```{r}


zebra_base <-  zebra_base %>%
  mutate(year = case_when(
     str_detect(Name, "2021") ~ 2021, 
    str_detect(Name, "2022") ~ 2022,
    TRUE ~ 2021),
    zeb_msc = str_extract(Name, " [:digit:]"),
    zeb_msc = ifelse(is.na(zeb_msc), 1, zeb_msc)
     )


#extract zebra lines and point data 
zebra_points <- zebra[st_geometry_type(zebra) == "POINT", ]
zebra_points$longitude <- st_coordinates(zebra_points)[,1]
zebra_points$latitude  <- st_coordinates(zebra_points)[,2]

zebra_lines <- zebra[st_geometry_type(zebra) == "LINESTRING", ]
zebra_lines$centroid <- st_centroid(zebra_lines$geometry)
zebra_lines$longitude <- st_coordinates(st_centroid(zebra_lines$geometry))[,1]
zebra_lines$latitude  <- st_coordinates(st_centroid(zebra_lines$geometry))[,2]

zebra_lines <- zebra_lines %>% dplyr::select(-centroid)
zebra_points <- rbind(zebra_points, zebra_lines)

zebra_base <- cbind(zebra_base, zebra_points)

zebra_base <- zebra_base %>% 
  dplyr::select(year, zeb_msc, longitude, latitude)


#fix individual cases
zebra_base$zeb_msc[2] <- 12
zebra_base$zeb_msc[24] <- 66


```

Populating Zebra_base with nearest geographic info
```{r}
?st_nearest_points

eco_base <- read_csv("https://raw.githubusercontent.com/ScubaDotTech/OpenAIS/refs/heads/main/Candlewood_Lake2025/SdT-CT_AIS-Geddy-Winter-2024/eco_base.csv")


eco_data <- st_as_sf(eco_base,coords = c("longitude", "lattitude"), crs = 4326) 
zeb_data <- st_as_sf(zebra_base,coords = c("longitude", "latitude"), crs = 4326) 

nearest_indices <- st_nearest_feature(zeb_data, eco_data) # find which rows have the closest points 
nearest_indeces <- as.data.frame(nearest_indices)


eco_zebra_geodata <- eco_data[nearest_indices, ] %>% dplyr::select(depth_m_,dfs_m_, substrate.code, -geometry)



zebra_base <- cbind(zebra_base, eco_zebra_geodata)
zebra_base <- zebra_base %>% drop_na() 
zebra_base <- zebra_base %>% dplyr::select(-geometry)
zebra_base

```

Second iteration of Zeb_MSC populations from 
```{r}
zeb_2022 <- read_csv("https://raw.githubusercontent.com/ScubaDotTech/OpenAIS/refs/heads/main/Candlewood_Lake2025/SdT-CT_AIS-Geddy-Winter-2024/zeb_msc_2022.csv")

zeb_2022 <- zeb_2022 %>%
  mutate(substrate.code = case_when( # give each substrate a numerical code based on hardness and density
    substrate == "Muck" ~ 1,
        substrate == "Organic" ~ 2,
            substrate == "Peat" ~ 3,
             substrate == "Silt" ~ 4,
                 substrate == "Sand" ~ 5,
                     substrate == "Gravel" ~ 6,
                         substrate == "Rock" ~ 7,
                           is.na(substrate) ~ NA  
  )
         )

zeb_2022_geom <- st_as_sf(zeb_2022,coords = c("longitude", "latitude"), crs = 4326) 


nearest_zeb_indices <- st_nearest_feature(zeb_2022_geom, eco_data) # find which rows have the closest points 
nearest_zeb_indices <- unlist(nearest_zeb_indices)  # Convert list to numeric vector
nearest_zeb_indices <- as.integer(nearest_zeb_indices) 

zeb_2022$depth_m_ <- eco_base$depth_m_[nearest_zeb_indices]
zeb_2022$dfs_m_ <- eco_base$dfs_m_[nearest_zeb_indices]


zebra_base <- as.data.frame(zebra_base)

zeb_2022 <- zeb_2022 %>% dplyr::select(-Point, -substrate)


setdiff(colnames(zeb_2022), colnames(zebra_base)) #troubleshoot 
zebra_base <- rbind(zebra_base, zeb_2022)

zebra_base


```

